name: Core
version: '${project.version}'
main: ac.stevano.core.Core
api-version: 1.8.8
load: POSTWORLD
commands:
  rank:
  grant:
  list:
  staffmode:
    aliases: [modmode, mod, staff, h]
permissions:
  core.command.rank:
    default: op
  core.command.grant:
    default: op
  core.command.list:
    default: not op